name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on tags that start with "v".

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PoeFixer.sln

      - name: Build project
        run: dotnet build PoeFixer.sln --configuration Release

      - name: Publish project
        run: dotnet publish PoeFixer.csproj -c Release -o ./output

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: ./output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
